apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hcp-user-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: hcp-user-service
  namespaceSelector:
    matchNames:
      - hcp
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
