alertmanager:
  enabled: false

grafana:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 6h
    scrapeInterval: 30s
    evaluationInterval: 30s
    resources:
      requests:
        cpu: 100m
        memory: 384Mi
      limits:
        cpu: 300m
        memory: 512Mi
    storageSpec: null

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 150m
      memory: 192Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 30m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 96Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 80m
      memory: 64Mi

defaultRules:
  create: true
  rules:
    kubeApiserver: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeProxy: false
    kubernetesStorage: false
    network: false